---
version: "3"
services:
    warpcore:
        container_name: warpcore
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - .:/opt/app
        environment:
            - BEANSTALKD_HOST=beanstalkd
            - BEANSTALKD_PORT=11300
    beanstalkd:
        image: placeloop/beanstalkd
        container_name: beanstalkd
        ports:
            - 11300:11300
        volumes:
            - .beanstalkd/data:/binlog
    beanstalkd-console:
        image: schickling/beanstalkd-console
        container_name: beanstalkd-console
        ports:
            - 2080:2080
