version: "3"
services:
    warpcore:
        container_name: warpcore
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/opt/app
